name: playground_1
description: 'A new Flutter project.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  home_widget: ^0.6.0
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  google_maps_flutter: ^2.6.1
  flutter_displaymode: ^0.6.0
  get_it_mixin: ^4.2.2
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  intl: any
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  http: ^1.2.1
  go_router: ^14.1.2
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  extra_alignments: ^1.0.0+1
  sized_context: ^1.0.0+4
  provider: ^6.1.2
  rnd: ^0.2.0
  package_info_plus: ^8.0.0
  flextras: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/_common/
    - assets/images/_common/icons/
    - assets/images/_common/texture/
    - assets/images/chichen_itza/
    - assets/images/christ_the_redeemer/
    - assets/images/colosseum/
    - assets/images/great_wall_of_china/
    - assets/images/machu_picchu/
    - assets/images/petra/
    - assets/images/pyramids/
    - assets/images/taj_mahal/
    - assets/images/collectibles/
    - assets/images/widget/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
